name: Deploy Docker Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Api Docker image
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          SHORT_SHA=${GITHUB_SHA:0:7}
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/gravity-api:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/gravity-api:$SHORT_SHA \
            . -f ./deploy/Dockerfile
      - name: Push Api Docker image (latest)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gravity-api:latest
      - name: Push Api Docker image (commit)
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          SHORT_SHA=${GITHUB_SHA:0:7}
          docker push ${{ secrets.DOCKER_USERNAME }}/gravity-api:$SHORT_SHA
      - name: Build Nginx Docker image
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          SHORT_SHA=${GITHUB_SHA:0:7}          
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/gravity-nginx:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/gravity-nginx:$SHORT_SHA \
            . -f ./deploy/Nginx.dockerfile
      - name: Push Nginx Docker image (latest)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gravity-nginx:latest
      - name: Push Nginx Docker image (commit)
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          SHORT_SHA=${GITHUB_SHA:0:7}
          docker push ${{ secrets.DOCKER_USERNAME }}/gravity-nginx:$SHORT_SHA
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Api Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/gravity-api:latest
      - name: Pull Nginx Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/gravity-nginx:latest
      - name: Delete existing Api Docker containers
        run: |
          sudo docker rm -f gravity-api-income || true
          sudo docker rm -f gravity-api-expense || true
      - name: Delete existing Nginx Docker container
        run: sudo docker rm -f gravity-nginx || true
      - name: Run Nginx and Api Docker containers
        run: |
          sudo docker run -d --name gravity-nginx -p 80:80 ${{ secrets.DOCKER_USERNAME }}/gravity-nginx:latest
          sudo docker run -d --name gravity-api-income -e api_port=8080 -e api_service=income -e environment=production ${{ secrets.DOCKER_USERNAME }}/gravity-api:latest
          sudo docker run -d --name gravity-api-expense -e api_port=8080 -e api_service=expense -e environment=production ${{ secrets.DOCKER_USERNAME }}/gravity-api:latest
