name: Deploy Docker Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHORT_SHA: ${{ github.sha[0:7] }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Api Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/gravity-api:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/gravity-api:${{env.SHORT_SHA}} \
            . -f ./deploy/Dockerfile
      - name: Push Api Docker image (latest)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gravity-api:latest
      - name: Push Api Docker image (commit)
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gravity-api:${{env.SHORT_SHA}}
      - name: Build Nginx Docker image
        run: |          
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/gravity-nginx:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/gravity-nginx:${{env.SHORT_SHA}} \
            . -f ./deploy/Nginx.dockerfile
      - name: Push Nginx Docker image (latest)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gravity-nginx:latest
      - name: Push Nginx Docker image (commit)
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gravity-nginx:${{env.SHORT_SHA}}